#!/usr/bin/env bash

[[ -n "$SSH_AUTH_SOCK" ]] || export SSH_AUTH_SOCK="/run/user/1000/ssh-agent"
if ssh-add -L | grep "The agent has no identities"
then
  ssh-add "$HOME/.ssh/id_rsa"
fi

BASE=$(dirname "$(readlink -f "$0")")
D=$(cut -f1 < "$BASE/details")
U=$(cut -f2 < "$BASE/details")
P=$(cut -f3 < "$BASE/details")

ssh -A -t "$D" ssh -A -t "$U"@localhost -p "$P" screen -DR
